export const themes = {
  normal: {
    id: 'normal',
    name: 'Normal',
    icon: '✨',
    description: 'Tema clásico morado',
    gradient: 'from-violet-600 via-purple-600 to-fuchsia-600',
    primary: 'from-purple-500 to-purple-600',
    secondary: 'from-violet-400 to-violet-600',
    accent: 'from-fuchsia-400 to-fuchsia-600',
    buttonBg: 'bg-purple-600',
    textPrimary: 'text-purple-600',
  },
  volleyball: {
    id: 'volleyball',
    name: 'Volleyball',
    icon: '🏐',
    description: 'Energía de cancha',
    gradient: 'from-yellow-500 via-blue-500 to-white',
    primary: 'from-yellow-400 to-yellow-600',
    secondary: 'from-blue-400 to-blue-600',
    accent: 'from-orange-400 to-orange-600',
    buttonBg: 'bg-yellow-500',
    textPrimary: 'text-yellow-600',
  },
  football: {
    id: 'football',
    name: 'Football',
    icon: '⚽',
    description: 'Campo verde',
    gradient: 'from-green-600 via-emerald-500 to-teal-600',
    primary: 'from-green-500 to-green-700',
    secondary: 'from-emerald-400 to-emerald-600',
    accent: 'from-teal-400 to-teal-600',
    buttonBg: 'bg-green-600',
    textPrimary: 'text-green-600',
  },
  anime: {
    id: 'anime',
    name: 'Anime',
    icon: '🌸',
    description: 'Colores vibrantes',
    gradient: 'from-pink-500 via-purple-500 to-cyan-500',
    primary: 'from-pink-400 to-pink-600',
    secondary: 'from-purple-400 to-purple-600',
    accent: 'from-cyan-400 to-cyan-600',
    buttonBg: 'bg-pink-500',
    textPrimary: 'text-pink-600',
  },
  basketball: {
    id: 'basketball',
    name: 'Basketball',
    icon: '🏀',
    description: 'Energía de cancha',
    gradient: 'from-orange-600 via-amber-500 to-orange-700',
    primary: 'from-orange-500 to-orange-700',
    secondary: 'from-amber-400 to-amber-600',
    accent: 'from-red-500 to-red-600',
    buttonBg: 'bg-orange-600',
    textPrimary: 'text-orange-600',
  },
};
